name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish_backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ./VuagilePointer.Backend
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      working-directory: ./VuagilePointer.Backend
      with:
        local: ./publish
        remote: /vuagile/backend/publish
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
      
  publish_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm install
        working-directory: ./VuagilePointer.Frontend
      - name: Build frontend
        run: npm run build:production
        working-directory: ./VuagilePointer.Frontend
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.5.3
        working-directory: ./VuagilePointer.Frontend
        with:
          local: dist
          remote: /vuagile/frontend
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
